### ISSUE TITLE
Selection of device/message type is not available in Java app

### ISSUE THREAD

**Issue by Liefersar** [SAP/iot-starterkit#10] opened 2015-10-07 21:34 UTC
Hello,
I tried to use the Java application but I can't select any device/message type data seen on the attached picture.

![bildschirmfoto 2015-10-07 um 23 03 44](https://cloud.githubusercontent.com/assets/15021901/10351634/efad599c-6d4a-11e5-8da0-465f17134b52.JPG)

Thanks for help.

Regards,
Sefa

**Comment by levinanton** [comment] 2015-10-08 05:56
Hello, 

can you please re-check the following configurations?

For "iotmms" java application:

- IoT-MMS-User role should be assigned to your HCP user (a user is specified without trial prefix)

![step1](https://cloud.githubusercontent.com/assets/12249110/10358693/5d2dcbf0-6d91-11e5-9b87-40a7f1385a4a.png)

- authentication configuration is "custom" and "user name and password" option is selected for "Form"

![step2](https://cloud.githubusercontent.com/assets/12249110/10358724/aedab31e-6d91-11e5-810d-bb6b39c45030.png)

For "starterkit" java application:

- "iotrdms" destination is present, you user is specified without trial prefix, password is correct and truststore is selected

![step3](https://cloud.githubusercontent.com/assets/12249110/10358758/eb4d4e2e-6d91-11e5-9fc0-0ae3184fa85d.png)

Regards,
Anton

P.S. Consider to restart the apps afterwards if you would need to do some changes.

**Comment by Liefersar** [comment] 2015-10-08 14:15
Hello Anton,
thanks for your answer.
All configurations except the authentication configuration were the same. I have edited it but unfortunately  after restart of both Java apps I got the same problem as well.

Regards,
Sefa

**Comment by levinanton** [comment] 2015-10-08 15:46
Hm, can you please then do the following:

- open your browser in incognito mode;
- access your starterkit app url: https://iotstarterkit<YOUR_USER_ID>trial.hanatrial.ondemand.com/com.sap.iot.starterkit.ui/ 
a SAP logon page should be shown, enter your credentials but do mark "remember me" option, submit;
- open a second tab in the same browser;
- access your iotmms app url: https://iotmms<YOUR_USER_ID>trial.hanatrial.ondemand.com/com.sap.iotservices.mms/ this should log on you automatically;
- in iotmms press logg off button (top right)
- go to first tab with "iotstarterkit" and refresh the page

Regards,
Anton

**Comment by Liefersar** [comment] 2015-10-08 19:08
There is no log off button. 

![bildschirmfoto 2015-10-08 um 21 04 33](https://cloud.githubusercontent.com/assets/15021901/10376851/6dd52966-6e00-11e5-95bf-d885991dd2f0.JPG)

Kind regards,
Sefa

**Comment by levinanton** [comment] 2015-10-08 19:12
Can you please update your MMS first? Click on top right tile to open IoT Cockpit. Version 2.3.0 should be available there.

**Comment by Liefersar** [comment] 2015-10-08 19:24
After refreshing the "iotstarterkit" page the logon page appears again.

**Comment by levinanton** [comment] 2015-10-08 19:26
And if you logon, then you get the same error message in UI?

**Comment by Liefersar** [comment] 2015-10-08 19:27
Yes, I get the same failure.

**Comment by levinanton** [comment] 2015-10-09 05:52
Hi Sefa,

may I please ask you to check one more thing for me? Open your IoT RDMS in the browser via https://iotrdmsiotservices-%YOUR_USER_ID%trial.hanatrial.ondemand.com/com.sap.iotservices.dms/v1/api/devices
The result should be a json string listing your devices, smth like [{"id":"5bded13c-7137-43ab-9091-434e14f62b24","name":"Demo Device","device_type":"0d961467a9ea302f7f7d"}]

Thanks for your patience,
Anton

**Comment by Liefersar** [comment] 2015-10-09 09:59
Sure
[{"id":"fb3da2c8-f56a-45e7-9776-dd213cf18189","name":"MyGroPi","device_type":"3cfc68719fd7b3719f34"}]

Kind regards,
Sefa

**Comment by rainaromit** [comment] 2015-10-09 14:39
Hello ,

Did you got any solution ? 

I am facing the same issue .

Thanks 
Romit

**Comment by levinanton** [comment] 2015-10-09 16:50
Hi Sefa, hi Romit,

the problem as you might guess is that "starterkit" app cannot authenticate itself against "rdms" via the destination. As a response it gets the html (logon page) instead of json (a list of devices). Unfortunately, I still cannot reproduce it on my side. Tried out all possible combinations with two browsers (Chrome and FF), incognito and normal mode and three RTs Java EE 6 Web Profile, Java Web and Java Web Tomcat 7.

Can you maybe try the "dirty" path?

- delete the "starterkit" java app completely
- deploy it new (a war file)
- import and configure destinations
- bind "starterkit" to "iotmms" schema
- start the "starterkit" java app

Thanks,
Anton

**Comment by Liefersar** [comment] 2015-10-13 21:55
I tried all what you said. Additionally I delete all Java apps, iotmms as well and deploy all step for step once again but nothing succeeded.
Do you have any other ideas? I'm not going to give up.

Thanks,
Sefa

**Comment by levinanton** [comment] 2015-10-14 06:24
Hi Sefa,

let's give another try and check if you can consume RDMS API with Postman Plugin for Chrome for example (not just entering a URL in browser like we did before but really with Authorization header)

![postman](https://cloud.githubusercontent.com/assets/12249110/10476315/e8500116-724c-11e5-81c6-a33c9e943877.png)

Regards,
Anton

**Comment by Liefersar** [comment] 2015-10-14 17:01
![bildschirmfoto 2015-10-14 um 18 57 12](https://cloud.githubusercontent.com/assets/15021901/10491240/dc66edd4-72a5-11e5-8d2b-509c013637dc.JPG)

Does it help?

Kind regards,
Sefa

**Comment by levinanton** [comment] 2015-10-14 18:25
Hi Sefa,

one more thing to check on account level in the HCP Cockpit.

Go to Trust -> Local Service Provider. The values should be as follows. If not then press Edit and change. Maybe, yet another restart of the "starterkit" app is necessary afterwards,.

![trust](https://cloud.githubusercontent.com/assets/12249110/10493467/af288d8a-72b1-11e5-8629-825d17b09b66.png)

Regards,
Anton

**Comment by Liefersar** [comment] 2015-10-14 18:40
The values are the same as yours.

Kind regards,
Sefa

**Comment by levinanton** [comment] 2015-10-15 06:21
Hi Sefa, 

can you please drop me a short e-mail (my address is visible now on my github profile page)? I would like to exchange our HCP accounts IDs. As a first step to check out the logs for your account.

Regards,
Anton

**Comment by lukazorc** [comment] 2015-10-16 06:41
Hello, 
I have a similar problem. When I go to the link of the java application I get this Error 
![image](https://cloud.githubusercontent.com/assets/11753479/10535192/ed321cc4-73e0-11e5-8738-317158c095ea.png)
500 Internal Server Error Failed to forward a GET response from the destination to an origin.

If I paste the link of rdms in the browser I get the json string. 
[{"id":"1764772f-f48c-43b8-8436-ff41348d7796","name":"RasPi2","device_type":"7fedb45c8b1dbb30796c"}]

If but if I open it in the Postman app I get 
Malformed JSON: Unexpected '<'

**Comment by lukazorc** [comment] 2015-10-16 06:51
Sorry, I get it right now in Postman. But the 500 Error still persists.

**Comment by levinanton** [comment] 2015-10-16 07:57
@lukazorc according to output it is a different problem. can you please make a screenshot of your destinations for "starterkit" app?

**Comment by lukazorc** [comment] 2015-10-16 08:01
![image](https://cloud.githubusercontent.com/assets/11753479/10536641/c758b9de-73ec-11e5-9931-87e02bd5d5c9.png)

**Comment by levinanton** [comment] 2015-10-16 09:59
@lukazorc In the logs I see that your "starterkit" tries to access the following RDMS link: https://iotrdmsiotservices-%YOUR-P-USER%trail.hanatrial.ondemand.com/com.sap.iotservices.dms/v1/api/devices  (where you have "trail" and not "trial" specified at the end you your P-USER). On the screenshot it is correct. If you have changed that typo after app was started, please consider to restart it.

I also see that "iotmms" URL is incorrect on the screenshot. "trial" postfix is missing at the end of your P-USER

Regards,
Anton

**Comment by gadregayatri** [comment] 2015-10-17 18:48
Hi,

I am also getting the same error after opening the GUI application. 
It was working totally fine before. I think it started giving an error after upgrading MMS to version 2.1. Now I have upgraded to the latest 2.3 version. Still I am facing the same issue. All the configurations are correct. 
Can you please help? 

Regards,
Gayatri

**Comment by levinanton** [comment] 2015-10-17 19:38
Hi Sefa, hi Gayatri,

can you pls check the following for me?

1. In HCP Cockpit -> Services -> Internet of Things Services -> Roles -> Unassign your HCP user from IoT-User role.
2. In starterkit UI you should get a message popup saying smth like "500 internal server error. failed to forward GET response..." and in the logs for "starterkit" app a message like "Server returned HTTP response code: 403 for URL: https://iotrdmsiotservices-%YOUR-USER-ID%trial.hanatrial.ondemand.com/com.sap.iotservices.dms/v1/api/devices"

Thanks,
Anton

**Comment by Liefersar** [comment] 2015-10-19 11:39
Hi Anton,

I get the same failure again. So nothing what you enumerate. 

Kind regards,
Sefa

**Comment by levinanton** [comment] 2015-10-20 11:51
@lukazorc according to logs, your configuration issue is resolved. can you please confirm shortly? Thanks, Anton

**Comment by levinanton** [comment] 2015-10-20 11:53
@gadregayatri @rainaromit can you please tell if an issue is still valid on your side? Thanks, Anton

**Comment by gadregayatri** [comment] 2015-10-22 06:03
I am still facing the same issue.

**Comment by levinanton** [comment] 2015-10-22 09:25
@gadregayatri Can you please drop me a mail (visible in my GitHub profile) and include your HCP account ID and the exported "iotrdms" destination file of your "starterkit" app? I create a list of accounts where that issue occurs.

Thanks,
Anton

**Comment by gadregayatri** [comment] 2015-10-26 04:43
Hi Anton,
I have emailed you the details.
Thank you for the help! :)

-Gayatri

**Comment by levinanton** [comment] 2016-09-05 13:08
Dear user(s),

this ticket is inactive since October 26, 2015. We are therefore closing it.
If your issue still persists, please feel free to reopen this ticket for further processing. In case you were asked to provide additional information by the processor, please do so when reopening the ticket.

Best regards,
IoT StarterKit Team

**Closed by levinanton** 2016-09-05 13:08 UTC
